---

- name: Make sure config directory exist
  file:
    path: "~{{ config_owner }}/.config/plank/dock1/launchers"
    state: directory
    owner: "{{ config_owner }}"
    group: "{{ config_owner_primary_group }}"
    mode: 0700

# This needs to be rewritten with regexp to find the launcher name from the file name
- name: Configure dock launchers
  template:
    src: "launcher.dockitem.j2"
    dest: "~{{ config_owner }}/.config/plank/dock1/launchers/{{ item.name }}.dockitem"
    owner: "{{ config_owner }}"
    group: "{{ config_owner_primary_group }}"
    mode: 0700
  with_items: "{{ plank_dock_items }}"

- name: Configure clippy item for plank
  template:
    src: clippy.dockitem.j2
    dest: "~{{ config_owner }}/.config/plank/dock1/launchers/clippy.dockitem"
    owner: "{{ config_owner }}"
    group: "{{ config_owner_primary_group }}"
    mode: 0700
  when: "{{ clippy_dock_item_on == true }}"

- name: Configure clock item for plank
  template:
    src: clock.dockitem.j2
    dest: "~{{ config_owner }}/.config/plank/dock1/launchers/clock.dockitem"
    owner: "{{ config_owner }}"
    group: "{{ config_owner_primary_group }}"
    mode: 0700
  when: "{{ clock_dock_item_on == true }}"

- name: Configure desktop item for plank
  copy:
    src: desktop.dockitem
    dest: "~{{ config_owner }}/.config/plank/dock1/launchers/desktop.dockitem"
    owner: "{{ config_owner }}"
    group: "{{ config_owner_primary_group }}"
    mode: 0700
  when: "{{ desktop_dock_item_on == true }}"

- name: Configure trash item for plank
  copy:
    src: trash.dockitem
    dest: "~{{ config_owner }}/.config/plank/dock1/launchers/trash.dockitem"
    owner: "{{ config_owner }}"
    group: "{{ config_owner_primary_group }}"
    mode: 0700
  when: "{{ desktop_dock_item_on == true }}"
  
