---
- name: Download plank from source
  get_url:
    url: https://launchpad.net/plank/1.0/0.11.4/+download/plank-0.11.4.tar.xz
    dest: /tmp/plank.tar.xz
    checksum: md5:d2405f33bfefd16ab80c868f83526f9b

- name: Update software cache for apt-get
  apt:
    update_cache: yes
  changed_when: false

- name: Install required software for compiling
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'xz-utils', state: 'present' }
  - { name: 'automake', state: 'present' }
  - { name: 'gnome-common', state: 'present' }
  - { name: 'intltool', state: 'present' }
  - { name: 'pkg-config', state: 'present' }
  - { name: 'valac', state: 'present' }
  - { name: 'libbamf3-dev', state: 'present' }
  - { name: 'libdbusmenu-gtk3-dev', state: 'present' }
  - { name: 'libgdk-pixbuf2.0-dev', state: 'present' }
  - { name: 'libgee-dev', state: 'present' }
  - { name: 'libglib2.0-dev', state: 'present' }
  - { name: 'libgtk-3-dev', state: 'present' }
  - { name: 'libwnck-3-dev', state: 'present' }
  - { name: 'libx11-dev', state: 'present' }
  - { name: 'libgee-0.8-dev', state: 'present' }

- name: Unpack plank source
  shell: 'tar xf plank.tar.xz'
  args:
    chdir: /tmp
  changed_when: False

- name: Run configure on plank source
  shell: ./configure
  args:
    chdir: /tmp/plank-0.11.4
  changed_when: False

- name: Run make on plank source
  make:
    chdir: /tmp/plank-0.11.4
  changed_when: False

- name: Run make install on plank source
  make:
    target: install
    chdir: /tmp/plank-0.11.4
  changed_when: False

- name: Run ldconfig
  shell: ldconfig
  args:
    chdir: /tmp/plank-0.11.4
  changed_when: False
