---

- name: Install software on Fedora
  when: ansible_distribution == 'Fedora'
  become: true
  dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'plank', state: 'present' }

- name: Update software cache for pacman
  when: ansible_distribution == 'ArchLinux'
  become: true
  pacman:
    update_cache: yes
  changed_when: false

- name: Install software on ArchLinux
  when: ansible_distribution == 'ArchLinux'
  become: true
  pacman:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'plank', state: 'present' }

- name: Update software cache for apt-get
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true
  apt:
    update_cache: yes
  changed_when: false

- name: Install software on Ubuntu
  when:
  - ansible_distribution == 'Ubuntu'
  - ansible_lsb.major_release|int >= 16 
  become: true
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'plank', state: 'present' }

- name: Install software on Debian
  when: ansible_distribution == 'Debian'
  become: true
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'plank', state: 'present' }
