---

- name: Install software on Fedora
  when: ansible_distribution == 'Fedora'
  become: true
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'plank', state: 'present' }

- name: Install software on openSUSE
  when: ansible_os_family == 'Suse'
  become: true
  community.general.zypper:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'plank', state: 'present' }
  - { name: 'plank-lang', state: 'present' }

- name: Update software cache for pacman
  when: ansible_distribution == 'ArchLinux'
  become: true
  community.general.pacman:
    update_cache: yes
  changed_when: false

- name: Install software on ArchLinux
  when: ansible_distribution == 'ArchLinux'
  become: true
  community.general.pacman:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'plank', state: 'present' }

- name: Update software cache for apt-get
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false

- name: Install software on Ubuntu
  when:
  - ansible_distribution == 'Ubuntu'
  - ansible_lsb.major_release|int >= 16
  become: true
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'plank', state: 'present' }

- name: Install software on Debian
  when: ansible_distribution == 'Debian'
  become: true
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'plank', state: 'present' }
